[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    fastled/FastLED @ ^3.7.0
    https://github.com/rstephan/ArtnetWifi
    bblanchon/ArduinoJson @ ^7.0.0

monitor_speed = 115200
upload_speed = 921600

# OTA upload: pio run -t upload -e esp32dev-ota
[env:esp32dev-ota]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = espota
upload_port = artnode.local
lib_deps = ${env:esp32dev.lib_deps}
